apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  selector:
    app: jenkins
  ports:
    - name: http
      port: 8080
      targetPort: http-port
    - name: jnlp
      port: 50000
      targetPort: jnlp-port
  type: NodePort  